### ISSUE TITLE
Dynamic mode can't work

### ISSUE THREAD

**Issue by terenceli** [twistlock/whoc#1]
@YuvalAvra Y
IIUC, the dynamic mode should work even if the runc has fixed CVE-2019-5736.

However, It don't work in my Ubuntu 20.04 host.

What's your test environment? The test runc has fixed CVE-2019-5736?

Thanks

**Comment by yuvalavra** [comment]
Hi @terenceli,
The dynamic mode only works for dynamically linked runtimes. You can run `ldd <runtime>` to check if it's dynamically linked.

**Comment by terenceli** [comment]
@YuvalAvra 

Yes, ldd /usr/sbin/runc shows as following:

root@ubuntu:/home/test/whoc# ldd /usr/sbin/runc 
	linux-vdso.so.1 (0x00007fff6f3a9000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f58c8e50000)
	libseccomp.so.2 => /lib/x86_64-linux-gnu/libseccomp.so.2 (0x00007f58c8dfd000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f58c8c0b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f58c8e86000)

So I think it should work in dynamic mode.

> Hi @terenceli,
> The dynamic mode only works for dynamically linked runtimes. You can run `ldd <runtime>` to check if it's dynamically linked.

**Comment by yuvalavra** [comment]
Tested with ubuntu 20.04, works on my GCP VM.

Can you try using my whoc image instead?
First shell:
```
./util/fileserver.py
```
Second shell:
```
docker run --rm --net=host -it yuvalavra/whoc:latest 127.0.0.1
```
If that doesn't work, can you share the output of the `docker run` command?

**Comment by terenceli** [comment]
> Tested with ubuntu 20.04, works on my GCP VM.

Useful information!

> 
> Can you try using my whoc image instead?

I totally uses the command in this repo.

> First shell:
> 
> ```
> ./util/fileserver.py
> ```
> 
> Second shell:
> 
> ```
> docker run --rm --net=host -it yuvalavra/whoc:latest 127.0.0.1
> ```
> 
> If that doesn't work, can you share the output of the `docker run` command?

The same as yours.
I successfully run it in ubuntu 18.04 host.
My environment is Ubuntu 20.04.2 iso and install it locally. 
I think there maybe do some tweak for poc. 
Anyway, I will try to debug it more.

Thanks.

**Comment by yuvalavra** [comment]
Got it, let me know if you find a bug. Could help to check whether the wait-for-exec mode works:

First shell:
```
./util/fileserver.py
```
Second shell:
```
docker run --rm --net=host --name whoc_test -it yuvalavra/whoc:waitforexec 127.0.0.1
```
Third shell:
```
docker exec -it whoc_test /proc/self/exe
```

**Comment by terenceli** [comment]
Hello @YuvalAvra 

When in Ubuntu 20.04

I have following output.

```
root@ubuntu:/home/test/whoc/test# uname -a
Linux ubuntu 5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
root@ubuntu:/home/test/whoc/test# docker run --rm -it --net=host whoc:latest 127.0.0.1
root@ubuntu:/home/test/whoc/test# dmesg 
[ 8229.345569] 19309 (entrypoint): Uhuuh, elf segment at 0000000000400000 requested but the memory is mapped already

```

Maybe related with the musl-gcc or kernel? need more debug.

BYW: the wait-for-exec works as expected.

Thanks,

**Comment by terenceli** [comment]
I have changed the 'upload_runtime.c' to build as a so(uses the 'gcc' instead of 'musl-gcc') and replace the '/lib/x86_64-linux-gnu/libseccomp.so.2'.
Finally it works.

**Comment by yuvalavra** [comment]
Nice workaround! 
I do want `whoc` to work with any runtime regardless of the libraries it uses, so I'll be looking into this bug in the future

**Comment by yuvalavra** [comment]
Hi @terenceli, can you please check whether `yuvalavra/whoc:ldfix` works?

**Comment by terenceli** [comment]
> Hi @terenceli, can you please check whether `yuvalavra/whoc:ldfix` works?

@YuvalAvra 
It works in my ubuntu 20.04 host!
What's the root cause?

Thanks

**Comment by yuvalavra** [comment]
> What's the root cause?

@terenceli

- Up until now `whoc`'s dynamic linker was an executable, and the kernel would map it on top of the process executable. I'm not actually 100% sure how this worked in retrospect, but it did.
- This Linux [commit](https://github.com/torvalds/linux/commit/a4ff8e8620d3f4f50ac4b41e8067b7d395056843) introduced `MAP_FIXED_NOREPLACE`, which [doesn't allow overlapping mapping](https://github.com/torvalds/linux/blob/5816b3e6577eaa676ceb00a848f0fd65fe2adc29/fs/binfmt_elf.c#L394) in certain scenarios, one of them is [when the dynamic linker is an executable](https://github.com/torvalds/linux/blob/5816b3e6577eaa676ceb00a848f0fd65fe2adc29/fs/binfmt_elf.c#L632). This is the root cause for the issue.
- The fix is to make `whoc`'s dynamic linker a shared library (the kernel handles mapping differently in this case). This introduced an issue with relocations - they were simply not happening. I believe that's because the dynamic linker is expected to handle it's own relocations.
- To handle the relocation issue I decided to create a dedicated, minimal dynamic linker. It's compiled without libc and without a plt section, so no relocations are needed. It opens `/proc/self/exe` and then executes `upload_runtime`. `upload_runtime` can then read the runtime from `/proc/self/fd/3/` and continue like before.

This new implementation is bulkier but less susceptible to issues from kernel changes. I'm sure there's an easier solution, but finding it is quite the rabbit hole. If anyone has more experience with linkers you're welcomed to have a go at this issue.

**Comment by yuvalavra** [comment]
@terenceli can you verify the latest version works for you? It's at `yuvalavra/whoc:latest`

**Comment by terenceli** [comment]
> @terenceli can you verify the latest version works for you? It's at `yuvalavra/whoc:latest`

@YuvalAvra It also works!

Thanks
